### ISSUE TITLE
Host and scheme is ignored if set

### ISSUE THREAD

**Issue by webmonger** [kjayasa/swagger-ts-client#15]
Currently the host and schemes are ignored when creating the URL so it will only attempt to make calls to localhost.

Current:
`
request.get("/path/to/data.json")
`

If host and scheme exist:
`
request.get("https://api.awesomesite.com/path/to/data.json")
`

**Comment by webmonger** [comment]
Just created a PR for this feature https://github.com/kjayasa/swagger-ts-client/pull/16

**Comment by kjayasa** [comment]
Merged PR #16
