### ISSUE TITLE
typesDefinitionRender file case sensitive

### ISSUE THREAD

**Issue by pradok** [kjayasa/swagger-ts-client#3]
Hi

`const typesDefinitionRender_1 = require("./renderer/typesDefinitionRender");` should be 
`const typesDefinitionRender_1 = require("./renderer/TypesDefinitionRender");` My linux machine in CI/CD pipeline fails on line 14 tsFromSwagger.js

Any chance this can be resolved sooner?

Cheers

**Comment by kjayasa** [comment]
fixed in commit 0dd0ba35490162dcaf9fdc1d0d05e676ed792b3f
