### ISSUE TITLE
Generator doesn't seem to respect path parameters

### ISSUE THREAD

**Issue by cjam** [kjayasa/swagger-ts-client#5]
First off, nice work on this package.  Secondly, I'm trying to generate a client that has path parameters and despite being in the context of the template, they are treated as query parameters.  Which for my backend doesn't work since it's expecting the parameters in the path.  I created a super simple handlebar helper that just converted the url into an interpolated string:

```js
    templateHelpers: {
        "toInterpolatedString": (url) => {
            return (url || "").replace("{", "${");
        }
    },
```

then in the template...

```handlebars
    {{#each operationGroup.operations}}
    public async {{operationName}}({{#joinList operationParams}} {{paramDisplayName}}:{{paramType}} {{/joinList}}):Promise<{{responsesType}}>{
        {{#if operationParams}}
            {{#some operationParams "op=>(!op.inBody && !op.inPath)"}}
        const params = { 
            {{#joinList this ",\n" "op=>(!op.inBody && !op.inPath)"}}
            "{{paramName}}":{{paramDisplayName}}{{/joinList}} 
        };
            {{/some}}
        {{/if}}
            const response = await this.agent.{{httpVerb}}(`{{{toInterpolatedString url}}}`)
                {{#some operationParams "op=>(!op.inBody && !op.inPath)"}}
                .query(params)
                {{/some}}        
                {{#filterList operationParams "op=>op.inBody" "1"}}
                .send({{paramDisplayName}})
                {{/filterList}} 
            return response.body as {{responsesType}};
```

It's an extremely naiive fix, but thought i'd share it anyways.  

Just had a thought that this will likely break if there are both path and query params.

**Comment by mail4andrey** [comment]
Better
`templateHelpers: {
	      "toInterpolatedString": (url) => {
			  return (url || "").replace(/{/g, "${");
	      }
      },`

**Comment by wolever** [comment]
Note to others who find this issue (as this bug doesn't seem to be fixed in the most recent NPM build): the patch above will only replace the first parameter. Instead, `/{/g` needs to be used:

```
    templateHelpers: {
      'toInterpolatedString': (url) => {
        return (url || '').replace(/{/g, '${')
      },
    },

```
