### ISSUE TITLE
basePath in swagger.json ignored in endpoint URL generation

### ISSUE THREAD

**Issue by poppa** [kjayasa/swagger-ts-client#7]
The `basePath` property in `swagger.json` doesn't seem to be acknowledged when the endpoint path is generated. So I end up with `request.get('/operation')` instead of `request('/api/v1/operation')`, where `/api/v1` is the `basePath` in my `swagger.json`.

I got around it by overriding `operation.templateFile`, but it seems like something that is easily fixed.

**Comment by wolever** [comment]
It doesn't seem like this has made it into the most recent version.

To recreate:

1. Run `swagger-ts-client@0.9.6` on this swagger spec: https://gist.github.com/wolever/9915414aa70b848a39465b8332d6a0ba
2. Notice that the URLs do not have the `/v1/` prefix:

```
        return new Promise<DebugResult>((resolve, reject) => {
            request
            .get("/debug")
```
